// Generated by CoffeeScript 1.6.2
/*
grunt-phpcpd

Copyright (c) 2013 Andreas Lappe
http://kaeufli.ch
Licensed under the BSD license.
*/

var exec, path;

path = require('path');

exec = (require('child_process')).exec;

exports.init = function(grunt) {
  var buildCommand, cmd, config, defaults, done, exports;

  exports = config = {};
  cmd = done = null;
  defaults = {
    bin: 'phpcpd',
    minLines: 5,
    minTokens: 70,
    exclude: false,
    names: '*.php',
    quiet: true,
    verbose: false,
    resultFile: false,
    maxBuffer: 200 * 1024,
    ignoreExitCode: false
  };
  buildCommand = function(dir) {
    cmd = path.normalize(config.bin);
    if (config.reportFile) {
      cmd += " --log-pmd " + config.reportFile;
    }
    cmd += " --min-lines " + config.minLines;
    cmd += " --min-tokens " + config.minTokens;
    if (config.exclude) {
      cmd += " --exclude " + config.exclude;
    }
    if (config.names) {
      cmd += " --names " + config.names;
    }
    if (config.quiet) {
      cmd += " --quiet";
    }
    if (config.verbose) {
      cmd += " --verbose";
    }
    return cmd += " " + dir;
  };
  exports.setup = function(runner) {
    var dir;

    dir = path.normalize(runner.data.dir);
    config = runner.options(defaults);
    cmd = buildCommand(dir);
    grunt.log.writeln("Starting phpcpd (target: " + runner.target.cyan + ") in " + dir.cyan);
    grunt.verbose.writeln("Execute: " + cmd);
    return done = runner.async();
  };
  exports.run = function() {
    var cmdOptions;

    cmdOptions = {
      maxBuffer: config.maxBuffer
    };
    return exec(cmd, cmdOptions, function(err, stdout, stderr) {
      if (stdout) {
        grunt.log.write(stdout);
      }
      if (err) {
        if (!config.ignoreExitCode) {
          grunt.fatal(err);
        }
      }
      return done();
    });
  };
  return exports;
};
