// Generated by CoffeeScript 1.6.2
/*
grunt-phpcpd

Copyright (c) 2013 Andreas Lappe
http://kaeufli.ch
Licensed under the BSD license.
*/
module.exports = function(grunt) {
  var phpcpd;

  phpcpd = (require('./lib/phpcpd')).init(grunt);
  return grunt.registerMultiTask('phpcpd', 'Run phpcpd', function() {
    phpcpd.setup(this);
    return phpcpd.run();
  });
};
